version: '3.8'

services:
  # This is the container the codespace runs in
  app:
    build:
      context: ..
      # Modify this container to install things that can't be installed as http://containers.dev/features
      dockerfile: .devcontainer/Dockerfile
    container_name: app

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:postgres
    network_mode: host

  #postgres:
  #  image: postgres:latest
  #  restart: unless-stopped
  #  volumes:
  #    - postgres-data:/var/lib/postgresql/data
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_DB: postgres
  #    POSTGRES_PASSWORD: postgres
  #  network_mode: host

  xtdb:
    image: ghcr.io/xtdb/xtdb:nightly
    container_name: xtdb
    restart: unless-stopped
    volumes:
      - xtdb-data:/var/lib/xtdb
    network_mode: host

volumes:
  postgres-data:
  xtdb-data:
